INSERT INTO email_record (email, record_id, content) VALUES 
('user1@example.com', 1, 'URGENT: Your account has been compromised. Click here to secure it now!'),
('user2@example.com', 2, 'Congratulations! You've won a cash prize. Provide your details to claim.'),
('user3@example.com', 3, 'Important: Verify your bank account immediately to avoid suspension.'),
('user4@example.com', 4, 'Exclusive offer! Limited time discount on financial services.'),
('user5@example.com', 5, 'Action required: Confirm your identity to prevent account closure.'),
('user6@example.com', 6, 'Your recent transaction is suspicious. Click to review.'),
('user7@example.com', 7, 'Claim your inheritance now! Provide personal details for processing.'),
('user8@example.com', 8, 'Security alert: Unusual login activity detected on your account.'),
('user9@example.com', 9, 'Final notice: Your subscription will be canceled without immediate action.'),
('user10@example.com', 10, 'You've been selected for a special offer. Redeem now!'),
('user11@example.com', 11, 'URGENT: Your password has been reset. Confirm your new password.'),
('user12@example.com', 12, 'Exclusive investment opportunity. Act now for high returns.'),
('user13@example.com', 13, 'Important message: Verify your email to avoid service disruption.'),
('user14@example.com', 14, 'Your account has been suspended. Click to reinstate.'),
('user15@example.com', 15, 'Immediate action required: Your account is at risk of closure.'),
('user16@example.com', 16, 'You've received a payment. Provide details to claim.'),
('user17@example.com', 17, 'Critical security update required for your account.'),
('user18@example.com', 18, 'Congratulations! You're eligible for a pre-approved loan.'),
('user19@example.com', 19, 'Your online purchase is incomplete. Click to finalize.'),
('user20@example.com', 20, 'You've been signed up for a premium service. Confirm or cancel now.');
