INSERT INTO ScamCategory (category_id, description, type) VALUES 
(1, 'Money Scam', 'Type 1'),
(2, 'Identity Theft', 'Type 2'),
(3, 'Investment Fraud', 'Type 3'),
(4, 'Credit Card Scam', 'Type 4'),
(5, 'Phishing Scam', 'Type 5'),
(6, 'Social Engineering Fraud', 'Type 6'),
(7, 'Personal Documents Theft', 'Type 7'),
(8, 'Art Fraud', 'Type 8'),
(9, 'Real Estate Scam', 'Type 9'),
(10, 'Luxury Watches Theft', 'Type 10'),
(11, 'Vehicle Purchase Scam', 'Type 11'),
(12, 'Electronics Fraud', 'Type 12'),
(13, 'Family Heirlooms Theft', 'Type 13'),
(14, 'Antiques Sale Deception', 'Type 14'),
(15, 'Collectibles Fraud', 'Type 15'),
(16, 'Precious Metals Scam', 'Type 16'),
(17, 'Business Assets Fraud', 'Type 17'),
(18, 'Education Savings Scam', 'Type 18'),
(19, 'Real Estate Deception', 'Type 19'),
(20, 'Intellectual Property Fraud', 'Type 20');
